# -*- coding: utf-8 -*-
"""GPU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJoZoXlIejYK4UkjvRt6qJqcEPgyszcT
"""

import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
tf.config.list_physical_devices('GPU')