# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PR0cHAEn_Pe_fUXzVA6_ZLWOUlCEPWxO
"""



#@title Testing
import torch
import sys
import sys; sys.argv=['']; del sys

import torch.nn.functional as F
import numpy as np
import os
import argparse

from scipy import misc 
from Src.SINet import SINet_ResNet50
from Src.utils.Dataloader import test_dataset
from Src.utils.trainer import eval_mae, numpy2tensor

parser = argparse.ArgumentParser()
parser.add_argument('--testsize', type=int, default=352, help='the snapshot input size')
parser.add_argument('--model_path', type=str,
                    default='/content/drive/MyDrive/SINet_40.pth')
parser.add_argument('--test_save', type=str,
                    default='/content/drive/MyDrive/Test/')
opt = parser.parse_args()

model = SINet_ResNet50().cuda()
model.load_state_dict(torch.load(opt.model_path))
model.eval()

for dataset in ['Test10']:
    save_path = opt.test_save + dataset + '/'
    os.makedirs(save_path, exist_ok=True)

    test_loader = test_dataset(image_root='/content/drive/MyDrive/video10/'.format(dataset),
                               gt_root='/content/drive/MyDrive/Tvideo10/'.format(dataset),
                               testsize=opt.testsize)
    img_count = 1
    f=np.zeros(test_loader.size)
    for iteration in range(test_loader.size):
        # load data
        image, gt, name = test_loader.load_data()
        gt = np.asarray(gt, np.float32)
        gt /= (gt.max() + 1e-8)
        image = image.cuda()
        # inference
        
        _, cam = model(image)
        # reshape and squeeze
        cam = F.upsample(cam, size=gt.shape, mode='bilinear', align_corners=True)
        cam = cam.sigmoid().data.cpu().numpy().squeeze()
        # normalize
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)
        #misc.imsave(save_path+name, cam)
        cv.imwrite(save_path+name, cam*255)
        # evaluate
        r=cam-gt
        mae = eval_mae(numpy2tensor(cam), numpy2tensor(gt))
       # calc_precision_recall(np.arange(gt),np.arange(cam))
        f[iteration]=mae
        # coarse score
        print('[Eval-Test] Dataset: {}, Image: {} ({}/{}), MAE: {}'.format(dataset, name, img_count,
                                                                           test_loader.size, mae))
        img_count += 1

print("\n[Congratulations! Testing Done]")